/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.NguoiDungController;
import Molder.NguoiDungModel;
import static java.awt.Frame.ICONIFIED;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AD
 */
public class TaiKhoanView extends javax.swing.JPanel {

    ArrayList<NguoiDungModel> list = new NguoiDungModel().getDuLieu();
    final String header[] = {"Ma Nguoi Dung", "Tai Khoan", "Mat Khau", "Vai Tro", "Trang Thai"};
    final DefaultTableModel tb = new DefaultTableModel(header, 0);

    ArrayList<NguoiDungModel> list1 = new NguoiDungModel().getDuLieu1();
    final String header1[] = {"Ma Nguoi Dung", "Tai Khoan", "Mat Khau", "Vai Tro", "Trang Thai"};
    final DefaultTableModel tb1 = new DefaultTableModel(header1, 0);

    /**
     * Creates new form TaiKhoanView
     */
    public TaiKhoanView() {
        initComponents();
        TaiTrang(list);
        TaiTrang1(list1);
    }

    public final void TaiTrang(ArrayList<NguoiDungModel> arr) {
        tb.getDataVector().removeAllElements();
        for (int i = 0; i < arr.size(); i++) {
            String trangThaiTaiKhoan = arr.get(i).getTrangThaiTaiKhoan() ? "On" : "Off";
            String nd[] = {arr.get(i).getMaNguoiDung(), arr.get(i).getTaiKhoan(), arr.get(i).getMatKhau(), arr.get(i).getVaiTro(), trangThaiTaiKhoan};
            tb.addRow(nd);
//            jTable1.setModel(tb);
        }
        jTable1.setModel(tb);
    }

    public final void TaiTrang1(ArrayList<NguoiDungModel> arr) {
        tb1.getDataVector().removeAllElements();
        for (int i = 0; i < arr.size(); i++) {
            String trangThaiTaiKhoan = arr.get(i).getTrangThaiTaiKhoan() ? "On" : "Off";
            String nd[] = {arr.get(i).getMaNguoiDung(), arr.get(i).getTaiKhoan(), arr.get(i).getMatKhau(), arr.get(i).getVaiTro(), trangThaiTaiKhoan};
            tb1.addRow(nd);
//            jTable1.setModel(tb);
        }
        jTable2.setModel(tb1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVaiTro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtMaND = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tài Khoản", "Mật Khẩu", "Trạng Thái", "Vai Trò"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Tìm");

        jButton1.setText("Xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtTim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKeyReleased(evt);
            }
        });

        jLabel1.setText("Tìm tài khoản:");

        jLabel2.setText("Tài Khoản:");

        jLabel3.setText("Mật Khẩu:");

        jLabel4.setText("Trạng Thái:");

        jLabel5.setText("Vai Trò:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tài Khoản", "Mật Khẩu", "Trạng Thái", "Vai Trò"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setText("Mã ND:");

        txtMaND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jButton2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaND, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtMaND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    int hienthi = 0;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        hienthi = jTable1.getSelectedRow();
        Display(hienthi);

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtTimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKeyReleased
        TaiTrang(timNguoiDungModel());
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new NguoiDungController(this).update(this);
        list = new NguoiDungModel().getDuLieu();
        list1 = new NguoiDungModel().getDuLieu1();
        jTable1.setModel(tb);
        jTable2.setModel(tb1);
        Display(hienthi);
        Display1(hienthi1);
        TaiTrang(list);
        TaiTrang1(list1);
        Reset();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//      new NguoiDungController(this).deleteTk(this);
//      list = new NguoiDungModel().getDuLieu();
//      jTable1.setModel(tb);
//        Display(hienthi);
        int option = JOptionPane.showConfirmDialog(jButton1, "Bạn có muốn xóa thông tin", "Thông báo", JOptionPane.YES_NO_OPTION, ICONIFIED);
//        JOptionPane.show
//    int p = JOptionPane.YES_NO_OPTION;
        if (option == JOptionPane.YES_OPTION) {
            new NguoiDungController(this).deleteTk(this);
            list = new NguoiDungModel().getDuLieu();
            list1 = new NguoiDungModel().getDuLieu1();
            jTable1.setModel(tb);
            jTable2.setModel(tb1);
            Display1(hienthi1);
            Display(hienthi);
            TaiTrang(list);
            TaiTrang1(list1);
            Reset();
        } else {
            this.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    int hienthi1 = 0;
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        hienthi1 = jTable2.getSelectedRow();
        Display1(hienthi1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtMaNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNDActionPerformed
    private void Reset() {
        txtMaND.setText("");
        txtMaND.setText("");
        txtTaiKhoan.setText("");
        txtMatKhau.setText("");
        txtVaiTro.setText("");
        txtTrangThai.setText("");
    }

    private void Display(int i) {
        NguoiDungModel nd = list.get(i);
        txtMaND.setText(nd.getMaNguoiDung());
        txtTaiKhoan.setText(nd.getTaiKhoan());
        txtMatKhau.setText(nd.getMatKhau());
        txtVaiTro.setText(nd.getVaiTro());
        String trangThaiTaiKhoan = nd.getTrangThaiTaiKhoan() ? "1" : "0";
        txtTrangThai.setText(trangThaiTaiKhoan);
    }

    private void Display1(int i) {
        NguoiDungModel nd = list1.get(i);
        txtMaND.setText(nd.getMaNguoiDung());
        txtTaiKhoan.setText(nd.getTaiKhoan());
        txtMatKhau.setText(nd.getMatKhau());
        txtVaiTro.setText(nd.getVaiTro());
        String trangThaiTaiKhoan = nd.getTrangThaiTaiKhoan() ? "1" : "0";
        txtTrangThai.setText(trangThaiTaiKhoan);
    }

    public final ArrayList<NguoiDungModel> timNguoiDungModel() {
        if (txtTim.equals("")) {
            return new NguoiDungModel().getDuLieu();
        } else {

// return new NguoiDungModel().getDuLieu();
            return new NguoiDungModel().timTaiKhoan(txtTim.getText());
//            list = NguoiDungModel().timTaiKhoan(txtTim.getText();
//            TaiTrang(list);
//            Display(hienthi);
//            TaiTrang(list);
        }

    }

    public NguoiDungModel getTaiKhoan() {
        String maNguoiDung = txtMaND.getText();
        String taiKhoan = txtTaiKhoan.getText();
        String matKhau = txtMatKhau.getText();
        String vaiTro = txtVaiTro.getText();
        boolean b = txtTrangThai.getText().equals("1");
//    Boolean trangThaiCongViec = Boolean.valueOf(txtTrangThai.getText());
        return new NguoiDungModel(maNguoiDung, taiKhoan, matKhau, vaiTro, b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtMaND;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtTrangThai;
    private javax.swing.JTextField txtVaiTro;
    // End of variables declaration//GEN-END:variables

}
